### PR TITLE
Port "Optimise suffocation"

### PR DESCRIPTION
**Pull request by MrIvanPlays**

### CODE REVIEW

**Review by ham1255 — APPROVED** [review]
i approve but will need rebase when #315 +  #317

**Comment by DoctaEnkoda** [comment]
What is the difference in performance? Do you have a graph or something to show the difference?

**Comment by ham1255** [comment]
didn't save test results but it as i would say 3% better

**Comment by ham1255** [comment]
wait a second this pufferfish patch

**Comment by ham1255** [comment]
#314 should re add it back https://github.com/pufferfish-gg/Pufferfish/blob/ver/1.19/patches/server/0008-Optimize-suffocation.patch

**Pull request closed without merging**
