### PR TITLE
Some improvements by interguess

### PR DESCRIPTION
**Pull request by JonasDevDE**
See commit history for changelog.

### CODE REVIEW

**Comment by PureGero** [comment]
Where does paperweight version 2.0-SNAPSHOT come from? The latest version is 1.5.12-SNAPSHOT

It should also be the same version as the upstream. Different versions may bring incompatibilities.

**Comment by JonasDevDE** [comment]
> Where does paperweight version 2.0-SNAPSHOT come from? The latest version is 1.5.12-SNAPSHOT
> 
> It should also be the same version as the upstream. Different versions may bring incompatibilities.

The latest version is 2.0.0-SNAPSHOT.
See here: https://repo.papermc.io/#browse/browse:maven-public:io%2Fpapermc

**Comment by PureGero** [comment]
2.0.0-SNAPSHOT belongs to the branch 'softspoon-v2', a WIP branch. The 'main' branch is at 1.5.12-SNAPSHOT.
https://github.com/PaperMC/paperweight/tree/softspoon-v2

**Comment by JonasDevDE** [comment]
> 2.0.0-SNAPSHOT belongs to the branch 'softspoon-v2', a WIP branch. The 'main' branch is at 1.5.12-SNAPSHOT. https://github.com/PaperMC/paperweight/tree/softspoon-v2

Did you tested if it doesnt works? (Works for all our peojects)

**Comment by PureGero** [comment]
It may seem to work now, but since it's a dev branch, it's not guaranteed to always work. Plus, it's best to use the same version as the upstream to ensure compatibility.

**Comment by JonasDevDE** [comment]
> It may seem to work now, but since it's a dev branch, it's not guaranteed to always work. Plus, it's best to use the same version as the upstream to ensure compatibility.

Should be 1.5.7-SNAPSHOT now. :D

**Comment by JonasDevDE** [comment]
Jo @PureGero, what's about this?

**Comment by PureGero** [comment]
Won't Dependabot just update Paperweight again?

Also, the build failed it seems.

**Comment by JonasDevDE** [comment]
> Won't Dependabot just update Paperweight again?
> 
> Also, the build failed it seems.

You can just close dependabot's pr, dunno why the build failes. Works on my pc.

**Comment by JonasDevDE** [comment]
> > Won't Dependabot just update Paperweight again?
> > Also, the build failed it seems.
> 
> You can just close dependabot's pr, dunno why the build failes. Works on my pc.

Checked it, the build fails because there is some stuff deprecated. But if you build it in your ide it should work. Only "red warnings".

**Comment by PureGero** [comment]
> Checked it, the build fails because there is some stuff deprecated. But if you build it in your ide it should work. Only "red warnings".

Nope, the error is `Unsupported class file major version 65`. This means you’ve added a java 21 dependency. This is a problem since we’re building for java 17.

**Comment by JonasDevDE** [comment]
> > Checked it, the build fails because there is some stuff deprecated. But if you build it in your ide it should work. Only "red warnings".
> 
> Nope, the error is `Unsupported class file major version 65`. This means you’ve added a java 21 dependency. This is a problem since we’re building for java 17.

Java 17 works for me as well.

**Pull request closed without merging**
