### PR TITLE
Update to Paper version 1.21.3

### PR DESCRIPTION
**Pull request by IanTapply22**
Updates the Paper/Minecraft version up to `1.21.3` from the previous version `1.20.1`. Additionally, this also bumps the version of the master.

### CODE REVIEW

**Comment by IanTapply22** [comment]
@PureGero How do you go about updating the patches for the version update? I think there are some that need to be updated because I'm getting come invalid object errors being thrown.

**Comment by IanTapply22** [comment]
Hey! Thank you for the fast response time, I'll go ahead and manually recreate the patch file and update this PR. Another question, I seem to be getting the following error thrown too when applying patches:
`Unresolved reference: mainCapabilityAttribute`
Is this somehow in relation to the broken patches?

**Comment by ProdPreva1l** [comment]
iirc its because the patch that has that method didnt apply

**Comment by IanTapply22** [comment]
Gotcha, last question too, is there a good way to recreate all the patch files?

**Comment by ProdPreva1l** [comment]
Not sure what you mean? `./gradlew rebuildPatches` will make patches from files added to git

**Comment by IanTapply22** [comment]
So I've been messing around a bit, and rebuild patches just triggers that same mainCapabilityAttribute error thrown from the applyPatches, any idea what's going on?

**Comment by IanTapply22** [comment]
How do you manually patch and recreate the patch? Is there a good an simple way that I'm missing @ProdPreva1l?

**Pull request closed without merging**
