### PR TITLE
Fix pistons

### LINKED ISSUE #275: Piston duplication does not work
This is definitely caused by MultiPiper, or more specifically the 0181 patch. Compiling with 0181 patch, the duplication breaks. Remove it, duplication works.

Snipaste_2022-10-10_08-08-11

### PR DESCRIPTION
**Pull request by MrIvanPlays**
Aims to fix #275

Please test. <3

### CODE REVIEW

**Comment by MrIvanPlays** [comment]
This also has the potential of fixing most piston-related problems. Maybe PistonMoveBlockEndPacket shall also be updated to feature the pushed block??

**Comment by MrIvanPlays** [comment]
Converted to draft due to having a report for a NPE. Still waiting on the error.

**Comment by ham1255** [comment]
```
[00:08:34 ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1569) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1405) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.setBlockEntity(net.minecraft.world.level.block.entity.BlockEntity)" because "world" is null
	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:253) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:998) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1818) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1804) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:703) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.setBlockEntity(net.minecraft.world.level.block.entity.BlockEntity)" because "world" is null

	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1550) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	... 5 more
[00:08:34 ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.setBlockEntity(net.minecraft.world.level.block.entity.BlockEntity)" because "world" is null
	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:253) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:998) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1818) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1804) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:703) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1550) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1405) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by MrIvanPlays** [comment]
> ```
> [00:08:34 ERROR]: Encountered an unexpected exception
> net.minecraft.ReportedException: Exception ticking world
> 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1569) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1405) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.setBlockEntity(net.minecraft.world.level.block.entity.BlockEntity)" because "world" is null
> 	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:253) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:998) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1818) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1804) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:703) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.setBlockEntity(net.minecraft.world.level.block.entity.BlockEntity)" because "world" is null
> 
> 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1550) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	... 5 more
> [00:08:34 ERROR]: 	Cause of unexpected exception was
> java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.setBlockEntity(net.minecraft.world.level.block.entity.BlockEntity)" because "world" is null
> 	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:253) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:998) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1818) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1804) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:703) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1550) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1405) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> ```

the exception doesn't match the code

**Comment by ham1255** [comment]
> > ```
> > [00:08:34 ERROR]: Encountered an unexpected exception
> > net.minecraft.ReportedException: Exception ticking world
> > 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1569) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1405) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> > Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.setBlockEntity(net.minecraft.world.level.block.entity.BlockEntity)" because "world" is null
> > 	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:253) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:998) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1818) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1804) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:703) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.setBlockEntity(net.minecraft.world.level.block.entity.BlockEntity)" because "world" is null
> > 
> > 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1550) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	... 5 more
> > [00:08:34 ERROR]: 	Cause of unexpected exception was
> > java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.setBlockEntity(net.minecraft.world.level.block.entity.BlockEntity)" because "world" is null
> > 	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:253) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:998) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1818) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1804) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:703) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1550) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1405) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> > ```
> 
> the exception doesn't match the code

as i said on discord it was mistake on my own

**Comment by MrIvanPlays** [comment]
> > > ```
> > > [00:08:34 ERROR]: Encountered an unexpected exception
> > > net.minecraft.ReportedException: Exception ticking world
> > > 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1569) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1405) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> > > Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.setBlockEntity(net.minecraft.world.level.block.entity.BlockEntity)" because "world" is null
> > > 	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:253) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:998) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1818) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1804) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:703) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.setBlockEntity(net.minecraft.world.level.block.entity.BlockEntity)" because "world" is null
> > > 
> > > 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1550) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	... 5 more
> > > [00:08:34 ERROR]: 	Cause of unexpected exception was
> > > java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.setBlockEntity(net.minecraft.world.level.block.entity.BlockEntity)" because "world" is null
> > > 	at net.minecraft.world.level.block.piston.PistonBaseBlock.triggerEvent(PistonBaseBlock.java:253) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.triggerEvent(BlockBehaviour.java:998) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.level.ServerLevel.doBlockEvent(ServerLevel.java:1818) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.level.ServerLevel.runBlockEvents(ServerLevel.java:1804) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:703) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1550) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1405) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1181) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[MultiPaper-Server-1.19.3-R0.1-SNAPSHOT-mojang-mapped.jar:git-MultiPaper-"f375f6f"]
> > > 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
> > > ```
> > 
> > 
> > the exception doesn't match the code
> 
> as i said on discord it was mistake on my own

ok. do this fix tnt dupers or not?

**Comment by ham1255** [comment]
Patch does nothing? i have tested the patch but it seems like same as original patch is in place.

**Comment by xymb-endcrystalme** [comment]
https://github.com/xymb-endcrystalme/MultiPaperPrivateDontShare/commit/2eda134dac2f8a309d9bd7a69a814ee79128d57d

I ported this patch to `1.19.2` and it seems to fail when TNT duping. Although no guarantees that I did something wrong...

**Comment by MrIvanPlays** [comment]
I'll try to find out why when I have some more time.

**Pull request closed without merging**
