### PR TITLE
Fix Pets can't teleport to owner if owner is external player

### LINKED ISSUE #291: Mobs that have FollowOwnerGoal [Cats, Wolfs, Parrots] are glitched between servers [2 issues]
## problem 1:
Pets teleportation across servers seems not working and can produce weird results like looking at the player far away

i have pinned out the issue in `NMS` in class  `net.minecraft.world.entity.ai.goal.FollowOwnerGoal`
which used by pets , 
method `#canTeleportTo(BlockPos pos)` is always returning false if owner is external player outside ticking chunks,
because inside that method it uses `WalkNodeEvaluator#getBlockPathTypeStatic(World, pos)` which always return `BLOCKED`
image
then looking at the method inside that class that method uses another method called `getBlockPathTypeRaw` which returns
`BLOCKED` when block state is `null` if chunk is not loaded or external chunk
image
image

~~i tried to fix this myself but it was bad fix, was simply calling `level.getChunkAt` and then get the block state from it which was bad for TPS, not sure if anybody have good way to fix this.~~

image

## problem 2:
When they teleport in same server whilst the owner is external  they can't be clicked unless a nearby player from ticking shard come.

Video:
https://www.youtube.com/watch?v=G6DSUHCeqQ4

### PR DESCRIPTION
**Pull request by ham1255**
fixes #291

### CODE REVIEW

**Comment by PureGero** [comment]
Is that a sync chunk load?

**Comment by ham1255** [comment]
Yes.... if was done with async way glitch persists

**Comment by PureGero** [comment]
Hmmm, surely there's a better way without having to load a chunk. Perhaps let the player's server check if their pets need teleporting, even if the player's server doesn't own the chunk

**Comment by ham1255** [comment]
> Hmmm, surely there's a better way without having to load a chunk. Perhaps let the player's server check if their pets need teleporting, even if the player's server doesn't own the chunk

I tried to look for better results but its something within the follow goal that checks block state which returns null, loading chunk makes block state not null.

**Comment by ham1255** [comment]
Linked issue of this pr has all information about block state thing

**Comment by ham1255** [comment]
Also this seems to effect mob teleporting to external servers in general

**Comment by ham1255** [comment]
Update: it seems async actually works updated the code.

**Pull request closed without merging**
