### PR TITLE
Add debug bossbar similar to purpur's tps bossbar

### PR DESCRIPTION
**Pull request by ham1255**
story behind this implementation, since i used purpur for some time now i loved that command which showed tps in bossbar which can give useful information if server is lagging or something.

* command is `/mptps`
* changes if player is on different chunk similar to `/mpdebug`
* shows Server id, TPS, MSPT
* shows local players by that server, `based on player who enabled debug chunk` 
* shows shows external players on that server `based on player who enabled debug chunk` 
* total players playing in all servers
* permission `multipaper.command.mptps`

video of it: https://www.youtube.com/watch?v=e_TgyYvpaiA

### CODE REVIEW

**Comment by DoctaEnkoda** [comment]
https://www.spigotmc.org/resources/tabtps-1-8-8-1-19-show-tps-mspt-and-more-in-the-tab-menu.82528/

**Comment by ham1255** [comment]
> https://www.spigotmc.org/resources/tabtps-1-8-8-1-19-show-tps-mspt-and-more-in-the-tab-menu.82528/

looks great but this pr is intended for Multi paper servers since that plugin won't show another shards *TPS*

**Comment by AnghiYt** [comment]
Change command in "/mptps". In mi opinion "/mpdebugbossbar" it's a bit ugly

**Comment by ham1255** [comment]
Tbh i thought same just shorter command might be a bit misleading..

**Comment by ham1255** [comment]
changed command name and also added more information
image

**Comment by PureGero** [comment]
This belongs in a plugin

**Pull request closed without merging**
