### PR TITLE
Set Pufferfish as upstream

### PR DESCRIPTION
**Pull request by kugge**
Deleted pufferfish/airplane patches (https://pastebin.com/BwThixJR) and set upstream to pufferfish with paperweight. (#314)

Need/Include @ham1255  #315 pull request

### CODE REVIEW

**Comment by kugge** [comment]
I used this script: https://gist.github.com/kugge/f106d76b559dc62d3f08605d531f249e
Which can apply MultiPaper's patches on (almost) any paper fork.

**Comment by ham1255** [comment]
You will need to update .github/workflows/upstream as updating ref task name changed.

**Comment by PureGero** [comment]
Needs a rebase (not sure why tho...?)

**Comment by kugge** [comment]
Deleted for #327

**Pull request closed without merging**
