### PR TITLE
General gradle build scripts improvements

### PR DESCRIPTION
**Pull request by ham1255**
* ~fix a problem in `yaml` dependencies~ was fixed by @PureGero  in https://github.com/MultiPaper/MultiPaper/commit/21842e5617daf7c02eccaee9374a6fde9eab59ce
* Fix being unable to generate dev bundle in MultiPaper paperweight and created publish publication for it.
* created publication for master protocol messaging module

### CODE REVIEW

**Comment by PureGero** [comment]
Can you provide a link to a guide explaining what the dev bundle is and how to use it?

**Comment by ham1255** [comment]
I cant find a guide, but dev bundle is thing can be used with paper weight userdev. 
this project might can explain it:
https://github.com/PaperMC/paperweight-test-plugin

**Comment by ham1255** [comment]
i just made master protocol messaging publication so it can be installed to maven local

**Comment by ham1255** [comment]
I have found dependencies problem in Dev Bundle 

for some reason its not including: 
* Master protocol Messages classes
* snakeyml lib

**Comment by ham1255** [comment]
Will reopen when this get merged 
https://github.com/PaperMC/paperweight/pull/163

**Pull request closed without merging**
