### PR TITLE
Fix server being online even if server fails to boot and during shutdown caused by watchdog thread or a crash

### LINKED ISSUE #276: Server doesn't shut down completely after a crash
Hi,

When my server crashes, it doesn't shut down completely until i kill it, so players cannot reconnect right away.
https://mclogs.minestrator.com/bydBmXf

### LINKED ISSUE #290: Server WatchDog is unable to shutdown the server.
For some odd reason during one of my tests, i lagged one of the servers for 70 seconds, Server watchdog kicked in and started the shutdown process but server would stay online  and wont shutoff like a hang and connections still active.

can be seen in logs i had to `ctrl + c to quit

## plugins:
* Chunky
* Crasher *made by me to sake of simulating server lags*

## Logs: 
https://pastebin.com/raw/sSV66BPJ

### PR DESCRIPTION
**Pull request by ham1255**
- [x] should shutdown during early server start, like eula is false etc.  
- [x] Normal server crash functions normally `like exception in server tick loop` etc *wasn't broken before but good to include it*
- [x] Fix shutdown process hang if server get killed by WatchDog

note: after fixed this bug with hang, there good? behavior that if watchdog killed the server while master is offline it will wait for master to be online then saves everything then exit.  
for example this logs:
```
[12:43:00 INFO]: [MultiPaperConnection] Connecting to localhost:35353...
[12:43:00 INFO]: Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
[12:43:00 ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
	at java.lang.Thread.stop(Thread.java:942) ~[?:?]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:924) ~[main/:?]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:790) ~[main/:?]
	at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:896) ~[main/:?]
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:233) ~[main/:?]
[12:43:00 INFO]: Stopping server
[12:43:00 INFO]: Saving players
[12:43:01 INFO]: [MultiPaperConnection] Connecting to localhost:35353...
[12:43:01 INFO]: Saving worlds
[12:43:02 INFO]: [MultiPaperConnection] Connecting to localhost:35353...
[12:43:03 INFO]: [MultiPaperConnection] Connecting to localhost:35353...
[12:43:04 INFO]: [MultiPaperConnection] Connecting to localhost:35353...
[12:43:05 INFO]: [MultiPaperConnection] Connecting to localhost:35353...
[12:43:05 INFO]: [MultiPaperConnection] Connected to localhost/127.0.0.1:35353
[12:43:05 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[12:43:05 INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[12:43:05 INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[12:43:05 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[12:43:05 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:43:05 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:43:05 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[12:43:05 INFO]: Flushing Chunk IO
[12:43:05 INFO]: Closing MultiPaper File Syncer
[12:43:05 INFO]: Closing Thread Pool
2022-11-22 12:43:05,087 Log4j2-AsyncAppenderEventDispatcher-1-Async WARN Advanced terminal features are not available in this environment
[12:43:05 INFO]: Closing Server
```

closes #290 
closes #276

### CODE REVIEW

**Comment by ham1255** [comment]
to fix the watchdog Crash hang on server close you need to investigate why shutdown logic during crash 
hangs at this  
```java
if (this.playerList != null) {
            MinecraftServer.LOGGER.info("Saving players");
            this.playerList.saveAll(); // <- hang is caused here if watchdog is stopping the server
            this.playerList.removeAll(this.isRestarting); // Paper
            try { Thread.sleep(100); } catch (InterruptedException ex) {} // CraftBukkit - SPIGOT-625 - give server at least a chance to send packets
        }
```

**Comment by MartijnMuijsers** [comment]
If there are any tasks posted to the main event loop (via `MinecraftServer.tell`) while watchdog has taken over control, they will be performed on watchdog thread. This is a bit dangerous, but because chunks can rely on this to save for example, Paper has chosen to do this so that at least there's a second chance for them to work correctly. See `MinecraftServer.wrapRunnable` for the implementation.

It appears `MCUtil.ensureMain` is not happy about this. Recommended fix if this is the cause: allow main-thread stuff to be called on watchdog thread. So `MCUtil.ensureMain` should not only allow the main thread, but also the watchdog thread. This may also need to be reflected in `TickThread.isTickThread` and other similar methods.

**Comment by ham1255** [comment]
I have looked into paper source code on this stop code and ensureMain they have same code structure and i tested lagging the server, till watchdog kicked in. And server sucessfully shuts off

**Comment by ham1255** [comment]
> If there are any tasks posted to the main event loop (via `MinecraftServer.tell`) while watchdog has taken over control, they will be performed on watchdog thread. This is a bit dangerous, but because chunks can rely on this to save for example, Paper has chosen to do this so that at least there's a second chance for them to work correctly. See `MinecraftServer.wrapRunnable` for the implementation.
> 
> It appears `MCUtil.ensureMain` is not happy about this. Recommended fix if this is the cause: allow main-thread stuff to be called on watchdog thread. So `MCUtil.ensureMain` should not only allow the main thread, but also the watchdog thread (add a `|| Thread.getCurrentThread() == MinecraftServer.SERVER.shutdownThread` or something like that). This may also need to be reflected in `TickThread.isTickThread` and other similar methods.

I have done what you said still exact same thing?

**Review by DoctaEnkoda — APPROVED** [review]

**Comment by ham1255** [comment]
will be reopened when dev branch get merged

**Pull request closed without merging**
